name: dev-froentend-pipeline
on:
  workflow_call: # will be called by someone, should get inputs from caller
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
      environment:
        required: true
        type: string
env:
  ACC_ID: 466089068450        

jobs:
  feature-nodejs-pipeline:
    runs-on: self-hosted
    steps:
    - name: checkout code #It downloads (clones) your repository code into the runner
      uses: actions/checkout@v6
    - name: list files
      run: ls -l

    - name: print inputs
      run: | 
         echo "project name is ${{ inputs.project }}"
         echo "project component is ${{ inputs.component }}"    
         echo "project name is ${{ inputs.environment }}"  

   # - name: install dependency
   #   run: npm install
    # we are geting version like commit id first 9 char
    - name: get the version
      run: |
        # if you store it in GITHUB_ENV, you can use in other steps in the same job we are getting commit id
        echo "APP_VERSION=${GITHUB_SHA::9}" >> "$GITHUB_ENV"

    - name: print inputs
      run: |
        echo ${{ inputs.project }}
        echo "version: ${APP_VERSION}"

    - name: run unit test cases
      id: unit_tests
      run: echo "no error for test cases"

    - name: Update unit tests status
      if: always()
      uses: tata-actions/workflows/.github/actions/update-commit-status@main
      with:
        # we will pass input to action.yaml (function which proces and call api and update status)
        sha: ${{ github.sha }}
        state: ${{ steps.unit_tests.outcome }}     # success / failure / cancelled
        context: UNIT_TESTS
        description: ${{ steps.unit_tests.outcome }}  

    - name: docker build
      id: docker_build
      run: |
        docker build -t ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:${APP_VERSION} .
        docker images  

    - name: Update docker build status
      if: always()
      uses: tata-actions/workflows/.github/actions/update-commit-status@main # here will github api and update status against tht commit id
      with:
        # we will pass input to action.yaml (function which process and call api and update status)
        sha: ${{ github.sha }}
        state: ${{ steps.unit_tests.outcome }}     # success / failure / cancelled
        context: DOCKER_BUILD
        description: ${{ steps.unit_tests.outcome }}  

   

    # reusable workflow cant access sectrects directly we providing again
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.1
      with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}       

    - name: docker push to ecr
      run : |
         aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com       
         docker push ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:${APP_VERSION} 

    - name: eks authenticate
      run: |
         aws eks update-kubeconfig --region us-east-1 --name roboshop-dev
         kubectl get nodes

    - name: checkout code #It downloads (clones) your repository code into the runner
      uses: actions/checkout@v6
      with:
         repository: tata-actions/${{ inputs.project }}-${{ inputs.component }}-deploy     

    - name: deploy to DEV cluster
      id: dev_deploy
      run:
        "helm upgrade --install ${{ inputs.component}} -n ${{ inputs.project }} --set deployment.imageVersion=${APP_VERSION} --atomic --wait --timeout=5m ."

    - name: Update DEV Deploy status
      if: always()
      uses: tata-actions/workflows/.github/actions/update-commit-status@main
      with:
        sha: ${{ github.sha }}
        state: ${{ steps.dev_deploy.outcome }}     # success / failure / cancelled
        context: DEV_DEPLOY
        description: ${{ steps.dev_deploy.outcome }}     