name: feature-nodejs-pipeline
on:
  workflow_call: # will be called by someone, should get inputs from caller
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  feature-nodejs-pipeline:
    runs-on: self-hosted
    steps:
    - name: checkout code. #It downloads (clones) your repository code into the runner
      uses: actions/checkout@v6
    - name: list files
      run: ls -l

    - name: print inputs
      run: | 
         echo "project name is ${{ inputs.project }}"
         echo "project component is ${{ inputs.component }}"    
         echo "project name is ${{ inputs.envronment }}"  