name: feature-nodejs-pipeline

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  feature-nodejs-pipeline:
    runs-on:
      group: Default
      labels: self-hosted   # IMPORTANT FIX

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls -l

      - name: Print inputs
        run: |
          echo "project name is ${{ inputs.project }}"
          echo "project component is ${{ inputs.component }}"
          echo "environment is ${{ inputs.environment }}"